# Generated by Django 3.2.4 on 2021-06-28 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='project',
        ),
    ]
